runtime: nodejs
env: flex
entrypoint: npm start

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

readiness_check:
  app_start_timeout_sec: 1000
