runtime: nodejs
env: flex
entrypoint: npm start

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
handlers:
- url: /api/.*
  secure: always
  script: auto
  redirect_http_response_code: 301
- url: /
  static_files: build/index.html
  upload: build/index.html
  secure: always
  redirect_http_response_code: 301
- url: /
  static_dir: build
- url: /static
  static_dir: build/static
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
